name: Docker Image CI



on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 * * * *'  # Ta vrstica pomeni, da se akcija izvede ob začetku vsake ure

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run flake8
      run: python notebooks/Naloga01-IIS/test.py

    - name: Run fetch_data.py
      run: python notebooks/Naloga01-IIS/fetch_data.py

    - name: Run pre_process.py
      run: python notebooks/Naloga01-IIS/pre_process.py

    - name: Install DVC
      run: pip install dvc


    - name: Set up DVC
      run: |
        git config user.name "Benjamin"
        git config user.email "benjamin.petelinek@gmail.com"
        dvc remote add origin https://dagshub.com/PetelinekBenjamin/ML.dvc -f
        dvc remote modify origin --local auth basic
        dvc remote modify origin --local user PetelinekBenjamin
        dvc remote modify origin --local password 30663408e580bdb3f66e074627577a040f36b5ff
      
    - name: Push to DVC
      run: |
        git rm -r --cached 'data/processed/europark_-_pobreška_c..csv'
        git commit -m "data/processed/europark_-_pobreška_c..csv"
        dvc add data/processed/europark_-_pobreška_c..csv
        dvc remote default origin
        dvc push -r origin
        
    - name: Commit and push
      run: |
        git add .
        git commit -m "Update changes"
        git push
        git commit -m "Update changes"
        git push
